### ISSUE TITLE
Remaining documentation TODO's

### ISSUE THREAD

**Issue by ErinCain** [CVPIA-OSC/fallRunDSM#22]
- [x] `Surv_juv_outmigration_sac_delta` (intercepts and coefficients) - Contact Cyril to ask for the sources for this submodel
- [x] `.Surv_juv_delta_contact_points`, `.surv_juv_rear_contact_points` - Coefficients from literature (need source)
- [x] `.Surv_juv_delta_total_diversions`, `.surv_juv_rear_total_diversions` - Coefficients from literature (need source)
- [x] #39
- [x] Finish vignettes with longer scripts for adult hatchery allocation, logistic temperature modeling and straying, link to appropriate docs
- [x] need source for `month_return_proportions`; update params doc
- [ ] #40
- [x] need source for `spawn_success_sex_ratio`; update params doc
- [x] need source for `spawn_success_fecundity`; update params doc

**Comment by InigoP** [comment]
Sending email to authors to inquire about source for .Surv_juv_delta_contact_points , .surv_juv_rear_contact_points, .Surv_juv_delta_total_diverted, .surv_juv_rear_total_diverted

**Comment by InigoP** [comment]
should the missing sources for the params: month_return_proportions,  mass_by_size_class, spawn_success_sex_ratio, spawn_success_fecundity be "Expert opinion from SIT members"?

**Comment by ergz** [comment]
> Sending email to authors to inquire about source for .Surv_juv_delta_contact_points , .surv_juv_rear_contact_points, .Surv_juv_delta_total_diverted, .surv_juv_rear_total_diverted

email has been sent asking about the two comments above.

**Comment by ergz** [comment]
all persisting docs todos have been converted to issues
